spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database: postgresql


